const donuts = [
  {
    donutName: "choclate",
    price: 15,
    rating: 3,
    img: "assets/img/Chocolate-1.png",
  },
  {
    donutName: "vanilla",
    price: 20,
    rating: 1,
    img: "assets/img/vanilla-ice.png",
  },
  {
    donutName: "strawberry",
    price: 35,
    rating: 5,
    img: "assets/img/strawberry.png",
  },
  {
    donutName: "fudge",
    price: 45,
    rating: 4,
    img: "assets/img/salted-caramell.png",
  },
  {
    donutName: "bacon",
    price: 55,
    rating: 5,
    img: "assets/img/bacon.PNG",
  },
  {
    donutName: "ribeye",
    price: 35,
    rating: 1,
    img: "assets/img/rib-eye.PNG",
  },
  {
    donutName: "chicken",
    price: 35,
    rating: 3,
    img: "assets/img/chicken.PNG",
  },
  {
    donutName: "pulledBeef",
    price: 45,
    rating: 4,
    img: "assets/img/pulled-beef.PNG",
  },
  {
    donutName: "krasse",
    price: 60,
    rating: 1,
    img: "assets/img/water-cress.png",
  },
  {
    donutName: "maskros",
    price: 45,
    rating: 2,
    img: "assets/img/dandelion.png",
  },
  {
    donutName: "majs",
    price: 60,
    price: 60,
    rating: 5,
    img: "assets/img/corn-hole.PNG",
  },
  {
    donutName: "sjögräs",
    price: 25,
    rating: 1,
    img: "assets/img/sea-weed.png",
  },
];
